structuretimers/urls.py
"""Routes."""

from django.urls import path

from . import views

app_name = "structuretimers"

urlpatterns = [
    path("", views.TimerListView.as_view(), name="timer_list"),
    path("add/", views.CreateTimerView.as_view(), name="add"),
    path("remove/<int:pk>", views.RemoveTimerView.as_view(), name="delete"),
    path("edit/<int:pk>", views.EditTimerView.as_view(), name="edit"),
    path("copy/<int:pk>", views.CopyTimerView.as_view(), name="copy"),
    path(
        "list_data/<str:tab_name>",
        views.TimerListDataView.as_view(),
        name="timer_list_data",
    ),
    path("detail/<str:pk>", views.TimerDetailDataView.as_view(), name="detail"),
    path(
        "select2_solar_systems/",
        views.Select2SolarSystemsView.as_view(),
        name="select2_solar_systems",
    ),
    path(
        "select2_structure_types/",
        views.Select2StructureTypesView.as_view(),
        name="select2_structure_types",
    ),
]

structuretimers/templates/structuretimers/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}

{% block page_title %}{% translate title %}{% endblock %}

{% block content %}
    <h2 class="text-center">{{ title }}</h2>
    <div class="col-lg-12 container">
        {% block details %}{% endblock %}
    </div>
{% endblock %}

structuretimers/templates/structuretimers/timer_confirm_delete.html
{% extends "allianceauth/base.html" %}
{% load i18n %}

{% block page_title %}{% translate "Delete Timer" %}{% endblock page_title %}

{% block content %}
    <div class="col-md-8 col-md-offset-2">
        <h1 class="page-header text-center">
            {% translate "Delete Structure Timer" %}
        </h1>
        <div class="container-fluid">
            <div class="row">
                <form action="" method="post" id="confirm-delete-form">
                    {% csrf_token %}
                    <p>
                        {% trans "Are you sure you want to delete timer this timer?" %}
                    </p>
                    <p>
                        <strong>{{ object }}</strong>
                    </p>
                    <input class="btn btn-danger" type="submit" value="{% translate 'Delete' %}" />
                    {% include 'structuretimers/partials/cancel_button.html' %}
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

structuretimers/templates/structuretimers/timer_create_form.html
{% extends "structuretimers/timer_edit.html" %}
{% load i18n %}

{% block submit_button_text %}
    {% translate "Create Timer" %}
{% endblock %}

structuretimers/templates/structuretimers/timer_detail.html
{% load i18n %}

<label for="timerboardTimer">{% translate "Timer" %}</label>
<p>{{ object }}</p>

<label for="timerboardImgScreenshot">{% translate "Image" %}</label>
<p>
    {% if object.details_image_url %}
    <a href="{{ object.details_image_url }}" target="_blank">
        <img id="timerboardImgScreenshot" class="img-responsive" alt="details image" src="{{ object.details_image_url }}"/>
    </a>
    {% else %}
    <span class="text-muted">-</span>
    {% endif %}
</p>

<label for="timerboardNotes">{% translate "Notes" %}</label>
<textarea id="timerboardNotes" class="form-control" rows="3" readonly>{{ object.details_notes }}</textarea>

structuretimers/templates/structuretimers/timer_edit.html
{% extends "structuretimers/base.html" %}
{% load bootstrap %}
{% load static %}
{% load i18n %}

{% block details %}
    <div class="col-md-8 col-md-offset-2">
        <div class="row">
            {% if form.errors %}
                <p class="text-danger">
                    <i class="fas fa-exclamation-triangle"></i>
                    <strong> {% translate "Please correct the input errors below" %}</strong>
                </p>
            {% endif %}
            <form id="add-timer-form" class="form-signin" role="form" action="" method="POST">
                {% csrf_token %}
                {{ form|bootstrap }}
                <br/>
                <p>
                    <i class="fas fa-asterisk"></i> {% translate "required fields" %}
                </p>
                <button class="btn btn-primary" type="submit">
                    {% block submit_button_text %}{% endblock %}
                </button>
                {% include 'structuretimers/partials/cancel_button.html' %}
            </form>
        </div>
    </div>

    <!-- share data with JS part -->
    <div
        id="dataExport"
        data-select2SolarSystemsUrl="{% url 'structuretimers:select2_solar_systems' %}"
        data-select2StructureTypesUrl="{% url 'structuretimers:select2_structure_types' %}">
    </div>
    {{ NIGHT_MODE|json_script:"night-mode-data" }}
    {{ LANGUAGE_CODE|json_script:"language-code-data" }}

{% endblock details %}

{% block extra_css %}
    <link href="{% static 'structuretimers/vendor/select2-4.1.0-beta.1/select2.min.css' %}" rel="stylesheet" />
    <link href="{% static 'structuretimers/vendor/select2-bootstrap-theme-0.1.0-beta.10/select2-bootstrap.min.css' %}" rel="stylesheet" />
    {% include "bundles/jquery-datetimepicker-css.html" %}
    <link href="{% static 'structuretimers/css/timer_edit.css' %}" rel="stylesheet" />
{% endblock extra_css %}

{% block extra_javascript %}
    <script type="application/javascript" src="{% static 'structuretimers/vendor/select2-4.1.0-beta.1/select2.min.js' %}"></script>
    {% include "bundles/jquery-datetimepicker-js.html" %}
    <script type="text/javascript" src="{% static 'structuretimers/js/timer_edit.js' %}"></script>
{% endblock extra_javascript %}

structuretimers/templates/structuretimers/timer_list.html
{% extends "structuretimers/base.html" %}
{% load static %}
{% load i18n %}
{% load evelinks %}

{% block details %}
    <div class="col-lg-12 text-center">
        <b>{% translate "Current Eve Time:" %}</b>&nbsp;<span id="current-time">{{ current_time }}</span>
    </div>

    <span class="pull-right">
        {% if perms.structuretimers.create_timer %}
            <a
                href="{% url 'structuretimers:add' %}"
                class="btn btn-success btn-tabs"
                title="{% translate 'Add new timer' %}">
                {% translate "Add Timer" %}
            </a>
        {% endif %}
    </span>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation"><a href="#preliminary" aria-controls="preliminary" role="tab" data-toggle="tab">{% translate "Preliminary" %}</a></li>
        <li role="presentation"><a href="#current" aria-controls="current" role="tab" data-toggle="tab">{% translate "Current" %}</a></li>
        <li role="presentation"><a href="#past" aria-controls="past" role="tab" data-toggle="tab">{% translate "Past" %}</a></li>
        <li class="dropdown pull-right">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                {% translate "Staging:" %} {{ selected_staging_system|default:"?" }} <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                {% for staging_system in stageing_systems %}
                    <li><a href="{% url 'structuretimers:timer_list' %}?staging={{ staging_system.eve_solar_system.name }}">
                        {{ staging_system }} ({{ staging_system.eve_solar_system.eve_constellation.eve_region }})
                        {% if staging_system.is_main %} {% translate "[MAIN]" %} {% endif %}
                    </a></li>
                {% empty %}
                    <li class="disabled"><a href="#">{% translate "No staging system configured." %}</a></li>
                {% endfor %}
            </ul>
        </li>
    </ul>

    <div class="panel panel-default panel-tabs">
        <div class="panel-body">
            <div class="tab-content">
                <!-- targets tab -->
                <div role="tabpanel" class="tab-pane" id="preliminary">
                    {% include 'structuretimers/partials/preliminary_list_table.html' %}
                    <p class="text-muted">
                        {% translate "This page contains potential future timers." %}
                    </p>
                </div>

                <!-- current structuretimers tab -->
                <div role="tabpanel" class="tab-pane" id="current">
                    {% include 'structuretimers/partials/timer_list_table.html' with tab_name='current' %}
                    <p class="text-muted">
                        {% blocktranslate %}Timers remain on this page for {{ max_hours_expired }} hours after they expired{% endblocktranslate %}
                    </p>
                </div>

                <!-- past structuretimers tab -->
                <div role="tabpanel" class="tab-pane" id="past">
                    {% include 'structuretimers/partials/timer_list_table.html' with tab_name='past' %}
                </div>
            </div>
            <p class="text-muted">
                {% translate "*: Distance from selected staging system:" %} {{ selected_staging_system|default:"?" }}
                ({{ selected_staging_system.eve_solar_system.eve_constellation.eve_region|default:"?" }})
            </p>
        </div>
    </div>

    <!-- modal to show timer details -->
    <div class="modal" id="modalTimerDetails" tabindex="-1" role="dialog" aria-labelledby="myModal">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="gridSystemModalLabel">{% translate "Timer details" %}</h4>
                </div>
                <div class="modal-body">
                    <div id="modal_div_spinner">
                        {% if NIGHT_MODE %}
                            <img src="{% static 'structuretimers/img/Spinner-1s-64px-dark.gif' %}" alt="Spinner"/>
                        {% else %}
                            <img src="{% static 'structuretimers/img/Spinner-1s-64px-light.gif' %}" alt="Spinner"/>
                        {% endif %}
                    </div>
                    <div id="modalContent" style="display: none"></div>
                    <div id="modalLoadError"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">{% translate "Close" %}</button>
                </div>
            </div>
        </div>
    </div>

    <!-- share data with JS part -->
    <div
        id="dataExport"
        data-listDataCurrentUrl="{% url 'structuretimers:timer_list_data' 'current' %}?staging={{ selected_staging_system.pk }}"
        data-listDataPastUrl="{% url 'structuretimers:timer_list_data' 'past' %}?staging={{ selected_staging_system.pk }}"
        data-listDataTargetUrl="{% url 'structuretimers:timer_list_data' 'preliminary' %}?staging={{ selected_staging_system.pk }}"
        data-getTimerDataUrl="{% url 'structuretimers:detail' 'pk_dummy' %}"
        data-titleSolarSystem="{% translate 'Solar System' %}"
        data-titleRegion="{% translate 'Region' %}"
        data-titleStructureType="{% translate 'Structure Type' %}"
        data-titleTimerType="{% translate 'Timer Type' %}"
        data-titleOwner="{% translate 'Owner' %}"
        data-titleObjective="{% translate 'Objective' %}"
        data-titleVisibility="{% translate 'Visibility' %}"
        data-hasPermOPSEC="{{ perms.structuretimers.opsec_access }}"
        data-dataTablesPageLength="{{ data_tables_page_length }}"
        data-dataTablesPaging="{{ data_tables_paging }}"
        data-tabId="{{ tab }}"
    >
    </div>

{% endblock details %}

{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
    <link rel="stylesheet" href="{% static 'structuretimers/css/global.css' %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static 'structuretimers/css/timer_list.css' %}" type="text/css" media="screen">
{% endblock extra_css%}

{% block extra_javascript %}
    {% include 'bundles/moment-js.html' with locale=True %}
    {% include 'bundles/datatables-js.html' %}
    {% include 'bundles/filterdropdown-js.html' %}
    <script type="application/javascript" src="{% static 'structuretimers/js/timer_list.js' %}"></script>
{% endblock extra_javascript %}

structuretimers/templates/structuretimers/timer_update_form.html
{% extends "structuretimers/timer_edit.html" %}
{% load i18n %}

{% block submit_button_text %}
    {% translate "Update Structure Timer" %}
{% endblock %}